### ISSUE TITLE
todo.md is still present when all code TODOs are removed

### ISSUE THREAD

**Issue by anvk** [pgilad/gulp-todo#19]
windows/gulp-todo v0.9.0

Hi there,
It seems that the file todo.md is not removed and still present in my project structure with the last snapshot of TODO comments the next time I run my `gulp todo` task even though I removed every TODO comment from my codebase.

My todo task:

``` javascript
gulp.task('todo', function() {
  return gulp.src(SRC + 'js/**/*.js')
    .pipe(todo())
    .pipe(gulp.dest(SRC))
    .on('error', gutil.log);
});
```

I wonder if it is by design? It is kinda annoying since you can find todo.md file in a pull request even though a developer cleaned/fixed all of them in the code.

**Comment by lefoy** [comment]
Sorry to reopen this issue, but would it be possible to have an option to delete the TODO.md file if all code TODOs are removed?

**Comment by pgilad** [comment]
Hi @lefoy no problem...
I'm extremely unsure about the *correct* (read: most useful) output of `gulp-todo` if todos are parsed and none are found.
I find that trying to delete files is (and should be) outside the scope of this plugin.

What you can do, is based on the number of comments (`gulp-todo` attaches `.todos` array to the vinyl outputted file) choose whether to output file or delete it from a stream.

See https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md#delete-files-in-a-pipeline

You will need to use that with a combination of [gulp-if](https://github.com/robrich/gulp-if)

Some something along the lines of:
```js
.pipe(gulpIf(function(file) {
  return file.todos && Boolean(file.todos.length);
}, vinylPaths(del), gulp.dest('./'));
```

Hope that makes sense, and let me know if it's works, I'd love to add it to the readme (and PR is welcome)
