### ISSUE TITLE
Inject list into README.md directly without the need for a template

### ISSUE THREAD

**Issue by binarykitchen** [pgilad/gulp-todo#33]
I do not want to clutter the root directory of my repos with too many folders or files, i.E. with a `readme.md.template`.

Would be great to have a new option where I can define a certain marker, i.E.

`insertAfter: '## TODOs'`

and this will put the whole TODO list into README.md after the header `## TODOs` on a new line.

**Comment by pgilad** [comment]
Hi,

Thanks for the request!

1. You don't need to store the templates in your root dir, just add them to `.templates/`.
2. Injecting into the same template means this plugin will need to develop functionality to detect template placeholder, delete placeholder contents and inject new contents, all are entirely unrelated to the core logic of this plugin - and adapter of [leasot](https://github.com/pgilad/leasot) for `gulp`.

The way to solve this problem, is to either find a `gulp-plugin` that can inject into an existing template (I would look into `gulp-inject`) and add it to the work stream, or make a new one that better suited for the job.

Either way I want to keep this plugin focused on doing it's main core logic - using `leasot` to parse files from a stream and output the results back to a stream using the specified reporter.

Hope that makes sense

**Comment by binarykitchen** [comment]
thanks for that. well, regarding `.templates/`, no thatnks, i do not want to clutter my repo with too many files and directories and keep it as tidy'n simple as possible.

fair enough, my request is probably out of scope of this plugin. i will have a look at `gulp-inject` and check out some possibilities. cheers!

**Comment by pgilad** [comment]
:clap:

**Comment by acarnwath** [comment]
@binarykitchen - Were you able to work around this?  What did your gulpfile end up looking like?

**Comment by binarykitchen** [comment]
nope, no workaround
