### ISSUE TITLE
Todos being generated in random order

### ISSUE THREAD

**Issue by rsumilang** [pgilad/gulp-todo#34]
Hello, I have an issue with working on multiple machines. I have my office workstation and my home workstation where I work on the same code. The todo generator seems to read in the files in different orders on both machines. The issue with this is that the TODO.md gets generated with todos in different orders on both machines and my source code manager is picking that up as a change in the file and wants to commit it. This is becoming a problem because I don't want list a lot of commits in my git repo and I don't want to always manually ignore the file every commit until there is a real change.

Both of my machines are macbook pros running os x 10.10.

**Comment by pgilad** [comment]
This looks to me like a race condition in the order the files are read in the gulp stream, and not necessarily a problem with `gulp-todo`.
I would recommend any sorting plugin (https://github.com/sirlantis/gulp-order or my very own https://github.com/pgilad/gulp-sort) and see if this persists

**Comment by rsumilang** [comment]
I've added what you suggested. Thanks @pgilad!
