### ISSUE TITLE
Support for .php files

### ISSUE THREAD

**Issue by bserem** [pgilad/gulp-todo#35]
Is there any way to make gulp-todo parse php files and create the resulting markdowns?

I'm working with Drupal, and I'm creating a Gulpfile that, as it matures, turns out to be an excelent asset in theme development. However, we have a lot of php files and during development we often add TODOs.

Thanks in advance

ps: awesome utility :)

**Comment by pgilad** [comment]
Are the valid comment types:
` /* comment */`
` // comment`

?

**Comment by bserem** [comment]
Not sure I understood your question...

When trying to run Gulp with todo and a file with .php extension it dies with this:
`extension .php is not supported`

My todos in .tpl.php files are like:
`<?php // TODO: blah ?>`
and in .php files are like:
```
/**
 * TODO
 * blah
 */
```
or
`//TODO: blah`

**Comment by pgilad** [comment]
Great, I'll give it a go soon :smile:

You're welcome to add a PR!

**Comment by bserem** [comment]
If I understand what is the source of the problem then I'll try to make one!

Thanks

**Comment by pgilad** [comment]
This is actually a bug for https://github.com/pgilad/leasot

**Comment by pgilad** [comment]
I'm on it. But currently won't support `#` style comments...

**Comment by pgilad** [comment]
Closed via https://github.com/pgilad/gulp-todo/commit/d47ed589484d0afb987958591d77faef1201dbf7

**Comment by bserem** [comment]
That was fast!!

**Comment by pgilad** [comment]
:clap:
