### ISSUE TITLE
Support for .twig files

### ISSUE THREAD

**Issue by lefoy** [pgilad/gulp-todo#36]
Is it possible to add .twig file support?
In .twig file comments looks like this:

````
<!-- TODO: Hey, I'm a todo! -->
````
or
````
{# TODO: Hey, I'm a todo! #}
````

Thanks ! :)

**Comment by pgilad** [comment]
Hey the correct place for this issue is: https://github.com/pgilad/leasot/issues
(As I've extracted the parser from this plugin to a separate module).

Anyway - the syntax is extremely similar to handlebars (which has it's own parser) so you can easily add a PR for supporting `.twig`
