### ISSUE TITLE
Allow HTML files

### ISSUE THREAD

**Issue by binarykitchen** [pgilad/gulp-todo#38]
```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: File: /.../videomail-client/examples/bad_browser.html - Extension .html is not supported
```

You know, you can write inline JS in HTML files and in my case, there are some TODO remarks. So I think, HTML files should be allowed.

**Comment by pgilad** [comment]
Hi - this should go in https://github.com/pgilad/leasot/issues !!

Anyway HTML support can include both HTML support and JS comments support

**Comment by binarykitchen** [comment]
they seem to have fixed it - can you bump the leasot version anytime soon?

**Comment by pgilad** [comment]
fixed by https://github.com/pgilad/gulp-todo/commit/a8c0dcbf5eb457b5593c7746a85f0ff4eacc0b26

**Comment by binarykitchen** [comment]
thx man

**Comment by pgilad** [comment]
no problem
