### ISSUE TITLE
TODO.md is not being written

### ISSUE THREAD

**Issue by peterver** [pgilad/gulp-todo#40]
After running my gulp build with the following setup 

```
...
.pipe($.todo({
    verbose: true,
    fileName: 'TODO.md',
    absolute: true
}))
...
```

I noticed that even though the todo's are shown in my cli, they are not being written to a TODO.md file anywhere.

Is there some preliminary setup that i need to do ?

**Comment by pgilad** [comment]
Yeah `gulp-todo` doesn't output a file to stream if there are no todos found, see this line:
https://github.com/pgilad/gulp-todo/blob/master/lib/reporter.js#L29

**Comment by pgilad** [comment]
Closing this, let me know if it's still not solved...
