### ISSUE TITLE
Support es files

### ISSUE THREAD

**Issue by binarykitchen** [pgilad/gulp-todo#41]
This for files going through Babel to ES6/7

Because I am getting this error

```
Error: File: /home/michael-heuberger/Development/xxx/gulp/load/modules.es - Extension .es is not supported
```

**Comment by pgilad** [comment]
what is `es`? is it just javascript?

**Comment by binarykitchen** [comment]
Babel converts these to js

**Comment by pgilad** [comment]
Hmm, this should go to [leasot](https://github.com/pgilad/leasot)
I'll add those there

**Comment by binarykitchen** [comment]
thanks
