### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by gandhiShepard** [pgilad/gulp-todo#42]
I just wanted to take the time to tell you that this is awesome! Great work!  I extended it to include .yaml easily. And we've been having fun extending it to report on other comment types too. Have a great weekend. Stay awesome!

![200-1](https://cloud.githubusercontent.com/assets/8546059/10556844/690bdcba-7457-11e5-853e-901fa0a232e2.gif)

**Comment by pgilad** [comment]
Hi thanks! I'm happy to hear that. If your extensions are useful, perhaps share them with other users of this plugin with a PR ? :smirk:

**Comment by pgilad** [comment]
Hey, thanks for the feedback, let me know if I can help further :smile:
