### ISSUE TITLE
Doesn't recognize todo comments in the end of line

### ISSUE THREAD

**Issue by JuhQ** [pgilad/gulp-todo#44]
Doesn't work
```
myCodeHere() # TODO: validate my insanity here
```

Works:
```
# TODO: validate my insanity here
myCodeHere()
```

Using the plugin on coffeescript

**Comment by pgilad** [comment]
This is intended behavior in [leasot](https://github.com/pgilad/leasot#comment-format) - comments need to be in a line of their own, otherwise, regexes get really complicated.

**Comment by JuhQ** [comment]
Sure but IMHO this plugin should support both ways, even if the regex is really complicated. Half of my todo comments are now missing.

**Comment by dgreene1** [comment]
Yea, I would love this feature too. :)  I always write my comments at the end of lines in javascript.

**Comment by lostthetrail** [comment]
This should at least be documented in the README.

**Comment by 2biazdk** [comment]
Would love to see this as well!
