### ISSUE TITLE
Using this project ... :-)

### ISSUE THREAD

**Issue by mikeerickson** [pgilad/gulp-todo#51]
Hey bud

Using this project for some legacy work and would like to output to console (in table format) ala the CLI and [webpack-todo-plugin](https://github.com/mikeerickson/todo-webpack-plugin)   Tried to set the `reporter` property but doesn't seem to use it?

```
.pipe(todo({reporter: 'table'))
```

Available in another approach? If not, I might just fork it and add it (or continue to use my CLI script)

```
    "todo": "./node_modules/.bin/leasot \"./**/*.js\" --ignore \"./node_modules/**/*\",\"./public/vendor/**/*\" --tags error,info || true"
```

**Comment by pgilad** [comment]
`table` reporter works, this is the way to use it:
```js
gulp.task('todo-json', function () {
    gulp.src('./**/*.js', {
        base: './'
    })
        .pipe(todo({
            reporter: 'table'
        }))
        .pipe(gulp.dest('./'));
});
```
Make sure there are files passing through the stream, and that you have at least 1 output `todo/fixme`.

Regarding your run script, it could be simplified much further:
` "todo": "leasot \"./**/*.js\" --ignore \"./{node_modules,public/vendor}/**/*\" --tags error,info || true"`

`leasot` works if you installed it locally (also globally). Otherwise I used brace expansion to join `node_modules` and `public/vendor`.

**Comment by mikeerickson** [comment]
@pgilad Hmmm, not producing any output on this end (I literally copy/pasted your script just to make sure).   And yes, there are definitely TODOs :-)

**Comment by pgilad** [comment]
do other reporters work with this same task config?

**Comment by mikeerickson** [comment]
@pgilad Here is a quick and dirty sample.  When the task runs, it does create the TODO.md file (but does not output to console as CLI does)

https://github.com/mikeerickson/gulp-todo-test

**Comment by mikeerickson** [comment]
@pgilad Also, your proposed run script does not work either.  I see what you are doing there (and it seems as it should work) 

My script produces

![image](https://cloud.githubusercontent.com/assets/183153/19736723/60ce5ede-9b65-11e6-90dc-2069111f342e.png)

Your script produces

![image](https://cloud.githubusercontent.com/assets/183153/19736786/9e01b40e-9b65-11e6-90f3-519c62cf9771.png)


![image](https://cloud.githubusercontent.com/assets/183153/19736752/7a7f1bca-9b65-11e6-80fb-34b4a8108827.png)

**Comment by pgilad** [comment]
I fixed your gulp script. You had a problem with the paths. (The filename addition was optional)
https://github.com/mikeerickson/gulp-todo-test/pull/1

Regarding brace expansion, perhaps it's not supported in negative patterns. I'll have to create a test case

**Comment by mikeerickson** [comment]
@pgilad Must be something else in the way of this?   When you run the script, does it output table to console?  In my case, it just creates the (now todo.txt) file.  If I remove the filename parameter, then it creates TODO.md

**Comment by mikeerickson** [comment]
@pgilad Here is what I see when running

```
$ gulp todo
```

After execution, there is a `todo.txt` file in root which contains the table outputted version

![image](https://cloud.githubusercontent.com/assets/183153/19738990/375ee826-9b6e-11e6-9225-66e90790ac6b.png)

**Comment by mikeerickson** [comment]
@pgilad Note: I am using gulp-todo 5.1.0 (assuming you are using the same version) 

And, for posterity, I am using leasot 4.2.0 installed globally

**Comment by pgilad** [comment]
Yeah, that's exactly how it should work. `gulp` works by moving vinyl files (or buffers) down through streams. You can output and console.log gulp streams, but it's generally not what it's meant for.

See http://stackoverflow.com/questions/27975129/console-log-to-stdout-on-gulp-events

**Comment by mikeerickson** [comment]
Yes, I understand all of that.  What I am trying to replicate is same thing mocha, eslint, etc would output when running same type of operation.  I want the result of todo.txt to display in console. 

I can surely open the created file and display it, was assuming that gulp-todo would perform similar (to tools outlined above)

**Comment by mikeerickson** [comment]
Don't sweat it, I will just apply one of a few workarounds I've used in the past.  Surely not a show stopper by any stretch.
