### ISSUE TITLE
--ignore support

### ISSUE THREAD

**Issue by mikeerickson** [pgilad/gulp-todo#52]
Also, it seems this does not support --ignore property as well?

```
    .pipe(todo({
      'ignore': ['./node_modules/**/*','./public/vendor/**/*'],
    }))
```

Working on a legacy project which uses <script> tags and all vendor files in `./public/vendor` directory so trying to skip those as well :-)

Have a groovy evening!

**Comment by mikeerickson** [comment]
@pgilad If you want me to update this project to address these items as well, let me know.  If you dont have time ;-)  Or, like I said, I could just continue using my bash scripts.

**Comment by pgilad** [comment]
Hey thanks for the update. `gulp` plugins expect the right files to be piped to them. So you can either use the right globs for getting the files, or just filter the vinyl files in stream (using something like `gulp-ignore`):
```js
// option 1
gulp.task('task', function() {
  gulp.src(['./**/*.js', '!./node_modules/**'])
    .pipe(todo())
    .pipe(gulp.dest('./dist/'));
});

// option 2
gulp.task('task', function() {
  gulp.src('./**/*.js')
    .pipe(jshint())
    .pipe(gulpIgnore.exclude('./custom.js'))
    .pipe(todo())
    .pipe(gulp.dest('./dist/'));
});
```

**Comment by mikeerickson** [comment]
@pgilad OK, this one is working (using option 1) and is creating the `TODO.md` file in the `./dist` directory.  Now, just need to figure out why I cant output to console and we are golden!
