### ISSUE TITLE
How to print TODOs to the console?

### ISSUE THREAD

**Issue by bennyn** [pgilad/gulp-todo#53]
Hello, I used [grunt-todo](https://github.com/leny/grunt-todo) to print TODOs to the screen:

![unbenannt](https://cloud.githubusercontent.com/assets/469989/20701162/beff08e8-b611-11e6-8600-005f66c8b38b.PNG)

How can I do that using "gulp-todo"? Because for me it creates a `TODO.md` file but it doesn't print the output to the screen when running `gulp todo`.

This is my configuration:

```javascript
gulp.task('todo', function() {
  gulp.src('src/main/ts/**/*.ts')
    .pipe(todo())
    .pipe(gulp.dest('./'));
});
```

**Comment by pgilad** [comment]
Are you sure you want to use `gulp-todo` for this case? if all you want is to print to console, you should use [leasot](https://github.com/pgilad/leasot)

**Comment by acarnwath** [comment]
You can use `verbose: true` to output to the console in addition to creating the file
