### ISSUE TITLE
Upgrade to the latest version of leasot library (4.7.0)

### ISSUE THREAD

**Issue by mickeypearce** [pgilad/gulp-todo#55]
Could you please upgrade the leasot dependency, I'd love to use the latest functionality with official release. :)
Thanks in advance.

**Comment by pgilad** [comment]
Thanks - fixed in https://github.com/pgilad/gulp-todo/commit/33c33e13b38215c85b9b4472875ef8002735e073

**Comment by mickeypearce** [comment]
Super. It works nice.

Sorry, off-topic -  but I love how I can jump directly to TODO comment line from my TODOs file. :link:
Recommend.
:smile:  
```
todo.reporter('markdown', {
      transformComment: (file, line, text, kind, ref) => {
        return `| [${file}](${file}#${line}) | ${line} | ${text}`;
      }
    })
```

**Comment by pgilad** [comment]
If you find it very useful - add a PR to the readme so people can enjoy it
