### ISSUE TITLE
Where to add `--ignore` options

### ISSUE THREAD

**Issue by mikeerickson** [pgilad/gulp-todo#59]
Trying to get this running but it always includes the `node_modules` directory. When I use from CLI, I use the `--ignore` option to ignore `node_modules`, how can I do the same using this plugin.

**Comment by pgilad** [comment]
`leasot` supports `--ignore` only on the CLI, not through the API interface. That said - when using `gulp` you simply need to pass the correct sources to `gulp-todo`. See https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpsrcglobs-options

```js
gulp.src(['js/**/*.js', 'test/**/*.js])
...
```

There are also ways to filter vinyl files in stream, see the `gulpIf` example (the last one) in https://github.com/pgilad/gulp-todo#usage

**Comment by mikeerickson** [comment]
Good enough, explains why I couldn’t find it in the docs or source code.  I will adjust the src glob to omit `node_modules`. Should have thought of that to begin with.

**Comment by mikeerickson** [comment]
That is the way I handle it in our `todo-webpack-plugin` just assumed it was supported in this gulp plugin.
